### ISSUE TITLE
"No Input Plugin Selected"

### ISSUE THREAD

**Issue by johnnyspork** [raphnet/mupen64plus-input-raphnetraw#12] opened 2020-03-20 20:25 UTC
Using the latest Mupen64Plus-GUI (windows x86), selecting the raphnetraw plugin results in "No Input Plugin Selected." I can use the default input plugin and map the controllers manually, but I'd much rather use your plugin. I hope this is an easy fix. Thanks for all the effort!

**Comment by PeterN64** [comment] 2021-02-18 12:41
Well no Answer nothing? Bought the Adapter and get the same Error "Failed to load input plugin" Iam using mupen64plus gui.

**Comment by raphnet** [comment] 2021-02-25 03:51
Is this a problem only with the gui? Does it work from the command-line with the instructions here?
https://www.raphnet.net/programmation/mupen64plus-input-raphnetraw/index_en.php#8

**Comment by PeterN64** [comment] 2021-02-27 03:49
Well the Problem is solved as the GUI guys added raphnet by there own and modified it abit. Its working great.

**Comment by loganmc10** [comment] 2021-02-27 03:52
The only modification in the GUI is the addition of this pending PR: https://github.com/raphnet/mupen64plus-input-raphnetraw/pull/11

**Comment by raphnet** [comment] 2021-02-27 04:40
Thank you, I finally merged the pull request.

**Closed** 2021-02-27 04:43 UTC
